server:
  port: 8088
spring:
  datasource:
#    url: jdbc:mysql://database-2.crisuim0869s.ap-southeast-1.rds.amazonaws.com:3306/shopapp?useSSL=false&serverTimezone=UTC
    url: jdbc:mysql://localhost:3306/shop-app
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
      dialect: org.hibernate.dialect.MySQL8Dialect
      format_sql: true
  servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB
  redis:
    host: localhost
    port: 6379
  flyway:
    locations: classpath:/db/migration,classpath:/dev/db/migration
    baseline-on-migrate: true
    baseline-version: 0
  # kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        "[spring.json.type.mapping]": "category:com.example.shopapp.models.Category"
    consumer:
      group-id: groupA
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
  messages:
    basename: i18n/messages
    encoding: UTF-8
api:
  prefix: api/v1
jwt:
  expiration: 2592000 #30days = 30 * 24 * 60 * 60
  secretKey: thduy2003SecretKey1511ebcaccab1555cac46ca878eda68464dawdbipogepmmeopkawkk6a44946opiu

logging:
  level:
    org:
      springframework:
        security: debug